In [585]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
from scipy.stats import norm
from sklearn.datasets import load_iris,make_spd_matrix
from math import sqrt,pi,exp
from scipy.stats import norm
from numpy import *

# Importing data

In [586]:
iris=load_iris()
iris_df=pd.DataFrame(iris['data'])
iris_labels=iris['target']
iris_df.shape
iris_df

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

# Parameters for Clusters 2,3 and 4

In [677]:
# 2 clusters
clusters=2
parameters = {
    'cluster_weights':np.asarray([1/clusters for i in range(clusters)]),
    'cluster_feature_mean':np.random.choice(np.asarray(iris_df).flatten(),(clusters,iris_df.shape[1])),
    'cluster_cov_matrix':[make_spd_matrix(iris_df.shape[1]) for i in range(clusters)]
}
parameters

{'cluster_weights': array([0.5, 0.5]),
 'cluster_feature_mean': array([[6.5, 5.4, 6.9, 1.5],
        [2.1, 4.4, 2.9, 1.4]]),
 'cluster_cov_matrix': [array([[ 0.75912933, -0.75046126, -0.29634266, -0.96639689],
         [-0.75046126,  1.84805291,  0.50750591,  1.69402811],
         [-0.29634266,  0.50750591,  0.82226733,  0.63266447],
         [-0.96639689,  1.69402811,  0.63266447,  2.37284087]]),
  array([[ 7.00567659e-01, -1.08028864e-01,  1.87137644e-01,
          -5.22687380e-02],
         [-1.08028864e-01,  3.66316366e+00,  7.21411284e-02,
           1.72354903e+00],
         [ 1.87137644e-01,  7.21411284e-02,  5.74341444e-01,
          -1.08270307e-03],
         [-5.22687380e-02,  1.72354903e+00, -1.08270307e-03,
           1.62176103e+00]])]}

In [642]:
# 3 clusters
clusters=3
parameters = {
    'cluster_weights':np.asarray([1/clusters for i in range(clusters)]),
    'cluster_feature_mean':np.random.choice(np.asarray(iris_df).flatten(),(clusters,iris_df.shape[1])),
    'cluster_cov_matrix':[make_spd_matrix(iris_df.shape[1]) for i in range(clusters)]
}
parameters

{'cluster_weights': array([0.33333333, 0.33333333, 0.33333333]),
 'cluster_feature_mean': array([[3.4, 3.1, 2.7, 5. ],
        [1.5, 5.6, 4.5, 5.1],
        [5.8, 1.4, 4.4, 5.2]]),
 'cluster_cov_matrix': [array([[ 0.83929526,  0.36971743, -0.48150972, -0.1594278 ],
         [ 0.36971743,  1.25513273, -1.25294468, -0.8734518 ],
         [-0.48150972, -1.25294468,  2.91648124,  1.47074829],
         [-0.1594278 , -0.8734518 ,  1.47074829,  1.80148941]]),
  array([[ 1.26321274, -0.38008219, -1.22940481, -0.99464857],
         [-0.38008219,  0.84320853,  0.33179328,  0.35803721],
         [-1.22940481,  0.33179328,  2.50739652,  1.54130105],
         [-0.99464857,  0.35803721,  1.54130105,  1.95526286]]),
  array([[ 2.50046674, -0.7647402 ,  1.18623816, -1.42949902],
         [-0.7647402 ,  0.54767251, -0.47039704,  0.45440474],
         [ 1.18623816, -0.47039704,  1.55385504, -0.84793293],
         [-1.42949902,  0.45440474, -0.84793293,  1.00699062]])]}

In [658]:
# 4 clusters
clusters=4
parameters = {
    'cluster_weights':np.asarray([1/clusters for i in range(clusters)]),
    'cluster_feature_mean':np.random.choice(np.asarray(iris_df).flatten(),(clusters,iris_df.shape[1])),
    'cluster_cov_matrix':[make_spd_matrix(iris_df.shape[1]) for i in range(clusters)]
}
parameters

{'cluster_weights': array([0.25, 0.25, 0.25, 0.25]),
 'cluster_feature_mean': array([[4.6, 6.8, 5.6, 3. ],
        [6.5, 3.4, 1.2, 1.3],
        [4.4, 3. , 5. , 5. ],
        [5.4, 3.4, 3.4, 3. ]]),
 'cluster_cov_matrix': [array([[ 0.99910251, -0.13000275, -0.92466903, -0.41501745],
         [-0.13000275,  0.95319627,  0.60324133,  0.44606158],
         [-0.92466903,  0.60324133,  3.44316997,  1.52380935],
         [-0.41501745,  0.44606158,  1.52380935,  0.92651402]]),
  array([[ 2.88370437e+00, -1.32432024e+00,  1.43375162e+00,
           3.89011123e-02],
         [-1.32432024e+00,  1.34103521e+00, -8.00774933e-01,
           2.02605414e-01],
         [ 1.43375162e+00, -8.00774933e-01,  1.60577916e+00,
           3.59581300e-04],
         [ 3.89011123e-02,  2.02605414e-01,  3.59581300e-04,
           3.43304422e-01]]),
  array([[ 0.70692879,  0.12680383, -0.11926086, -0.16581293],
         [ 0.12680383,  1.5847579 ,  1.69861598,  0.33796413],
         [-0.11926086,  1.69861598,  3.77

# EM Algorithm

In [611]:
def iris_expectation_maximization(df,parameters):
    
    try:
        for i in range(20):
            count=0
            means=parameters['cluster_feature_mean']
            probable=[]
            covariance=parameters['cluster_cov_matrix']
            for j in range(clusters):
                probable.append(multivariate_normal.pdf(x=iris_df,mean=means[j],cov=covariance[j]))
    #             probable.append(norm_pdf_multivariate(x=iris_df, mu=means[j], sigma=covariance[j]))


            probable = np.array(probable)
            print(f'likelyhood length ={len(probable.flatten())}')
            predictions = np.argmax(probable, axis=0)
            build=[]
            weights=parameters['cluster_weights']
            
            for max_cluster in range(clusters):
                build.append((probable[max_cluster] * weights[max_cluster]) / (np.sum([probable[i] * weights[i] for i in range(clusters)], axis=0)))
                print(f'before={parameters["cluster_feature_mean"]}')
                parameters['cluster_feature_mean'][max_cluster]= np.sum(build[max_cluster].reshape(iris_df.shape[0],1) * iris_df, axis=0) / (np.sum(build[max_cluster]))
                print(f' after ={parameters["cluster_feature_mean"]}')
                parameters['cluster_cov_matrix'][max_cluster]=np.dot((build[max_cluster].reshape(iris_df.shape[0],1) * (iris_df - means[max_cluster])).T, (iris_df - means[max_cluster])) / (np.sum(build[max_cluster]))
                parameters['cluster_weights'][max_cluster]=np.mean(build[max_cluster])
#                 predicted_cluster.count(max_cluster)/iris_df.shape[0]

            
    #         print(parameters)
            print(set(predictions))
    except Exception as E:
        print(E)
        return predictions
        

    return predictions
            
            
    

# Predicitons on using EM algorithm

In [678]:
# clusters =2
y_2actual=iris_expectation_maximization(iris_df,parameters)
fig=px.scatter(iris_df,x=0,y=1,color=list(map(lambda x:x+1,y_2actual)))
fig.show()

likelihood length =300
before=[[6.5 5.4 6.9 1.5]
 [2.1 4.4 2.9 1.4]]
 after =[[6.50827758 2.96022434 5.21000364 1.8137356 ]
 [2.1        4.4        2.9        1.4       ]]
before=[[6.50827758 2.96022434 5.21000364 1.8137356 ]
 [2.1        4.4        2.9        1.4       ]]
 after =[[6.50827758 2.96022434 5.21000364 1.8137356 ]
 [5.1657583  3.1564308  2.27806884 0.57313174]]
{0, 1}
likelihood length =300
before=[[6.50827758 2.96022434 5.21000364 1.8137356 ]
 [5.1657583  3.1564308  2.27806884 0.57313174]]
 after =[[6.42846582 2.93482693 5.12672452 1.77668627]
 [5.1657583  3.1564308  2.27806884 0.57313174]]
before=[[6.42846582 2.93482693 5.12672452 1.77668627]
 [5.1657583  3.1564308  2.27806884 0.57313174]]
 after =[[6.42846582 2.93482693 5.12672452 1.77668627]
 [5.13445707 3.20833647 2.09417058 0.49792912]]
{0, 1}
likelihood length =300
before=[[6.42846582 2.93482693 5.12672452 1.77668627]
 [5.13445707 3.20833647 2.09417058 0.49792912]]
 after =[[6.37333922 2.91894668 5.06325578 1.747193

In [645]:
# 3 clusters
y_3actual=iris_expectation_maximization(iris_df,parameters)
fig=px.scatter(iris_df,x=0,y=1,color=list(map(lambda x:x+1,y_3actual)))
fig.show()

In [659]:
# 4 clusters
y_4actual=iris_expectation_maximization(iris_df,parameters)
fig=px.scatter(iris_df,x=0,y=1,color=list(map(lambda x:x+1,y_4actual)))
fig.show()

likelihood length =600
before=[[4.6 6.8 5.6 3. ]
 [6.5 3.4 1.2 1.3]
 [4.4 3.  5.  5. ]
 [5.4 3.4 3.4 3. ]]
 after =[[5.49596676 3.65572588 2.27870002 0.59475183]
 [6.5        3.4        1.2        1.3       ]
 [4.4        3.         5.         5.        ]
 [5.4        3.4        3.4        3.        ]]
before=[[5.49596676 3.65572588 2.27870002 0.59475183]
 [6.5        3.4        1.2        1.3       ]
 [4.4        3.         5.         5.        ]
 [5.4        3.4        3.4        3.        ]]
 after =[[5.49596676 3.65572588 2.27870002 0.59475183]
 [5.1307393  3.31976364 1.81695272 0.37859798]
 [4.4        3.         5.         5.        ]
 [5.4        3.4        3.4        3.        ]]
before=[[5.49596676 3.65572588 2.27870002 0.59475183]
 [5.1307393  3.31976364 1.81695272 0.37859798]
 [4.4        3.         5.         5.        ]
 [5.4        3.4        3.4        3.        ]]
 after =[[5.49596676 3.65572588 2.27870002 0.59475183]
 [5.1307393  3.31976364 1.81695272 0.37859798]
 [6.6

# Accuracy calculations for clusters 2,3 and 4

In [629]:
from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score

def kmeans(clusters,X):
    model = KMeans(n_clusters=clusters)
    clusters_labels = model.fit_predict(X)
    return clusters_labels
    
y_predict_3means=kmeans(3,iris_df)
y_predict_2means=kmeans(2,iris_df)
y_predict_4means=kmeans(4,iris_df)

In [679]:
# 2 clusters  accuracy with kmeans
accuracy_score(y_pred=y_2actual,y_true=y_predict_2means)

0.98

In [644]:
# 3 clusters accuracy with kmeans
accuracy_score(y_pred=y_3actual,y_true=y_predict_3means)

0.8133333333333334

In [660]:
# 4 clusters accuracy with kmeans
accuracy_score(y_pred=y_4actual,y_true=y_predict_4means)

0.6066666666666667

# References
## 1. 1-d GMM https://towardsdatascience.com/how-to-code-gaussian-mixture-models-from-scratch-in-python-9e7975df5252